import MSWProvider from "@/src/shared/msw-provider"
import QueryProvider from "@/src/shared/query-provider"
import Sidebar from "@/src/template/Sidebar"
import { Provider } from "jotai"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWProvider>
          <QueryProvider>
            <Provider>
              <Sidebar />
              {children}
            </Provider>
          </QueryProvider>
        </MSWProvider>
      </body>
    </html>
  )
}
